"""Add meta_data JSONB column to projects and meetings tables

Revision ID: 223a11211585
Revises: c1d6ed1a60d0
Create Date: 2025-09-25 18:13:05.018015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "223a11211585"
down_revision: Union[str, None] = "c1d6ed1a60d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings",
        sa.Column(
            "meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "meta_data")
    op.drop_column("meetings", "meta_data")
    # ### end Alembic commands ###
