"""Update meeting model for scheduling with Google Calendar integration

Revision ID: 3ba5065ab4e4
Revises: 223a11211585
Create Date: 2025-09-25 20:07:35.032874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ba5065ab4e4"
down_revision: Union[str, None] = "97e920014a77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meetings", sa.Column("project_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "meetings",
        sa.Column(
            "attendees", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "documentation_links",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "additional_information", sa.String(length=2000), nullable=True
        ),
    )
    op.add_column(
        "meetings",
        sa.Column(
            "google_calendar_event_id", sa.String(length=255), nullable=True
        ),
    )
    op.add_column(
        "meetings", sa.Column("status", sa.String(length=50), nullable=True)
    )
    op.alter_column(
        "meetings",
        "title",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "meetings",
        "description",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "meetings",
        "start_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "meetings",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "meetings",
        "meeting_link",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "meetings", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "meetings", type_="foreignkey")
    op.alter_column(
        "meetings",
        "meeting_link",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "meetings",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "meetings",
        "start_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "meetings",
        "description",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "meetings",
        "title",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_column("meetings", "status")
    op.drop_column("meetings", "google_calendar_event_id")
    op.drop_column("meetings", "additional_information")
    op.drop_column("meetings", "documentation_links")
    op.drop_column("meetings", "attendees")
    op.drop_column("meetings", "project_id")
    # ### end Alembic commands ###
