"""add pid to meeting table

Revision ID: 65e2bdc17ec0
Revises: 3ba5065ab4e4
Create Date: 2025-09-26 01:38:44.021245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e2bdc17ec0'
down_revision: Union[str, None] = '3ba5065ab4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'pid')
    # ### end Alembic commands ###
