"""add_external_link_to_documents

Revision ID: 7e6714770a31
Revises: 2cf5e69cea1c
Create Date: 2025-09-25 01:31:09.770540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6714770a31'
down_revision: Union[str, None] = '2cf5e69cea1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('external_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'external_link')
    # ### end Alembic commands ###
