"""add_doc_type_and_meeting_relationship

Revision ID: 97e920014a77
Revises: 223a11211585
Create Date: 2025-09-25 20:35:19.538504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e920014a77'
down_revision: Union[str, None] = '223a11211585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('meeting_id', sa.Integer(), nullable=True))
    
    # Create the enum type first
    documenttype_enum = sa.Enum('FILE', 'JIRA', 'CONFLUENCE', name='documenttype')
    documenttype_enum.create(op.get_bind())
    
    # Add doc_type column with default value for existing records
    op.add_column('documents', sa.Column('doc_type', documenttype_enum, nullable=True))
    
    # Update existing records to have FILE as default doc_type
    op.execute("UPDATE documents SET doc_type = 'FILE' WHERE doc_type IS NULL")
    
    # Make doc_type NOT NULL after setting defaults
    op.alter_column('documents', 'doc_type', nullable=False)
    
    op.create_foreign_key(None, 'documents', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'meeting_id')
    
    # Drop the enum type
    documenttype_enum = sa.Enum('FILE', 'JIRA', 'CONFLUENCE', name='documenttype')
    documenttype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
