"""Add projects table and project_id to documents

Revision ID: c1d6ed1a60d0
Revises: 6f106230ac2c
Create Date: 2025-09-25 17:19:02.449987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1d6ed1a60d0"
down_revision: Union[str, None] = "6f106230ac2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create projects table
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)

    # Add project_id column to documents table
    op.add_column(
        "documents", sa.Column("project_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "documents", "projects", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key and project_id column from documents
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "project_id")

    # Drop projects table
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
