"""Add projects table and project_id to documents

Revision ID: c1d6ed1a60d0
Revises: 6f106230ac2c
Create Date: 2025-09-25 17:19:02.449987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1d6ed1a60d0"
down_revision: Union[str, None] = "6f106230ac2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("project_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "documents", "projects", ["project_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "project_id")
    # ### end Alembic commands ###
