"""add source to document table

Revision ID: e1e840973c81
Revises: 65e2bdc17ec0
Create Date: 2025-09-26 02:53:33.915942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e840973c81'
down_revision: Union[str, None] = '65e2bdc17ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
